---
title: promise
date: 2017-01-24 11:11:13
categories:
  - 历史
  - 前端
tags:
- ES6
- promise
---
简单介绍一下promise
<!--more-->
### 基本用法
```bash
let promise = new Promise((resolve,reject)=>{
    /**业务处理**/
    resolve(/**data**/);
})
promise.then((data)=>{
    /**数据处理**/
}).catch((err)=>{
    /**错误处理**/
})
```

### promise常规用法

- promise.then

```bash
var promise = new Promise(resolve,reject){
    resolve('传递给then的值')
}
promise.then(function(data){
    console.log(data);
},function(error){
    console.log(error);
})
```

- promise.catch

```bash
var promise = new Promise(function(resolve, reject){
    resolve("传递给then的值");
});
promise.then(function (value) {
    console.log(value);
}).catch(function (error) {
    console.error(error);
});
```
- promise.resolve

```bash
function asyncTask(name){
    return Promise.resolve(name).then(function(value){
        return "Done"+value
    })
}
var taskName = "task 1";
asyncTask(taskName).then(function(value){
    console.log(value)
}).catch(function(err){
    console.log(err);
})
```

- promise.reject

```bash
var r = Promise.reject(new Error('err'))
```
- promise.all

```bash
var p1 = Promise.resolve(1),
    p2 = Promise.resolve(2),
    p3 = Promise.resolve(3);
Promise.all([p1, p2, p3]).then(function (results) {
    console.log(results);  // [1, 2, 3]
});
```
- promise.race

```bash
var p1 = Promise.resolve(1),
    p2 = Promise.resolve(2),
    p3 = Promise.resolve(3);
Promise.race([p1, p2, p3]).then(function (results) {
    console.log(results);  // [1]
});
```

### Promise.resolve()
*Promise.reject(error)是和 Promise.resolve(value) 类似的<mark>静态方法</mark>，是 new Promise() 方法的快捷方式。*


```bash
    Promise.resolve(42).then(function(value){
    console.log(value);
});
```

> 简单总结一下 Promise.resolve 方法的话，可以认为它的作用就是将传递给它的参数填充（Fulfilled）到promise对象后并返回这个promise对象。
此外，Promise的很多处理内部也是使用了 Promise.resolve 算法将值转换为promise对象后再进行处理的。

### Promise.reject()

```bash
Promise.reject(new Error("出错了"))
//是下面代码的语法糖
new Promise(function(resolve,reject){
    reject(new Error("出错了"));
});
```
> 它和Promise.resolve(value) 的不同之处在于promise内调用的函数是reject而不是resolve，这在编写测试代码或者进行debug时，说不定会用得上。


### 几个很重要的原则问题
- 绝对不能对异步回调函数（即使在数据已经就绪）进行同步调用。

- 如果对异步回调函数进行同步调用的话，处理顺序可能会与预期不符，可能带来意料之外的后果。

- 对异步回调函数进行同步调用，还可能导致栈溢出或异常处理错乱等问题。

- 如果想在将来某时刻调用异步回调函数的话，可以使用 setTimeout 等异步API。

**简单一句话：Promise只能使用异步调用方式 。**

- 不合法的调用
```bash
function onReady(fn) {
    var readyState = document.readyState;
    if (readyState === 'interactive' || readyState === 'complete') {
        fn();
    } else {
        window.addEventListener('DOMContentLoaded', fn);
    }
}
onReady(function () {
    console.log('DOM fully loaded and parsed');
});
console.log('==Starting==');
//控制台打印
DOM fully loaded and parsed
==Starting==
```
- 符合规范
```bash
function onReady(fn) {
    var readyState = document.readyState;
    if (readyState === 'interactive' || readyState === 'complete') {
        setTimeout(fn, 0);
    } else {
        window.addEventListener('DOMContentLoaded', fn);
    }
}
onReady(function () {
    console.log('DOM fully loaded and parsed');
});
console.log('==Starting==');
//控制台打印

<mark>Starting</mark>
DOM fully loaded and parsed
```
- 上述例子用promise重写
> 由于Promise保证了每次调用都是以异步方式进行的，所以我们在实际编码中不需要调用 setTimeout 来自己实现异步调用。


```bash
function onReadyPromise() {
    return new Promise(function (resolve, reject) {
        var readyState = document.readyState;
        if (readyState === 'interactive' || readyState === 'complete') {
            resolve();
        } else {
            window.addEventListener('DOMContentLoaded', resolve);
        }
    });
}
onReadyPromise().then(function () {
    console.log('DOM fully loaded and parsed');
});
console.log('==Starting==');
```
对于为什么请看[这里](http://effectivejs.com/).

### promise chain
- 基本用法
> 在本例中我们在taskA中使用了 throw 方法故意制造了一个异常。但在实际中想主动进行onRejected调用的时候，应该返回一个Rejected状态的promise对象。

```bash
function taskA() {
    console.log("Task A");
    throw new Error("throw Error @ Task A")
}
function taskB() {
    console.log("Task B");// 不会被调用
}
function onRejected(error) {
    console.log(error);// => "throw Error @ Task A"
}
function finalTask() {
    console.log("Final Task");
}

var promise = Promise.resolve();
promise
    .then(taskA)
    .then(taskB)
    .catch(onRejected)
    .then(finalTask);
//控制台打印
Task A
Error: throw Error @ Task A
Final Task
```
- promise chain 中如何传递参数
> 前面例子中的Task都是相互独立的，只是被简单调用而已。
这时候如果 Task A 想给 Task B 传递一个参数该怎么办呢？
答案非常简单，那就是在 Task A 中 return 的返回值，会在 Task B 执行时传给它。

```bash
function doubleUp(value) {
    return value * 2;
}
function increment(value) {
    return value + 1;
}
function output(value) {
    console.log(value);// => (1 + 1) * 2
}

var promise = Promise.resolve(1);
promise
    .then(increment)
    .then(doubleUp)
    .then(output)
    .catch(function(error){
        // promise chain中出现异常的时候会被调用
        console.error(error);
    });
```
### Promise.catch()
> 实际上 Promise#catch 只是 promise.then(undefined, onRejected); 方法的一个别名而已。 也就是说，这个方法用来注册当promise对象状态变为Rejected时的回调函数。

**在ECMAScript 3中保留字是不能作为对象的属性名使用的。 而IE8及以下版本都是基于ECMAScript 3实现的，因此不能将 catch 作为属性来使用，也就不能编写类似 promise.catch() 的代码，因此就出现了 identifier not found 这种语法错误了。
而现在的浏览器都是基于ECMAScript 5的，而在ECMAScript 5中保留字都属于 IdentifierName ，也可以作为属性名使用了。**
<mark>解决Promise#catch标识符冲突问题</mark>
- 使用`[]`而不使用`.`
```bash
var promise = Promise.reject(new Error("message"));
promise["catch"](function (error) {
    console.error(error);
});
```
- 使用 then也是可以避免这个问题的
```bash
var promise = Promise.reject(new Error("message"));
promise.then(undefined, function (error) {
    console.error(error);
});
```
### 每次调用then都会返回一个新创建的promise对象

```bash
// 1: 对同一个promise对象同时调用 `then` 方法
var aPromise = new Promise(function (resolve) {
    resolve(100);
});
aPromise.then(function (value) {
    return value * 2;
});
aPromise.then(function (value) {
    return value * 2;
});
aPromise.then(function (value) {
    console.log("1: " + value); // => 100
})

// vs

// 2: 对 `then` 进行 promise chain 方式进行调用
var bPromise = new Promise(function (resolve) {
    resolve(100);
});
bPromise.then(function (value) {
    return value * 2;
}).then(function (value) {
    return value * 2;
}).then(function (value) {
    console.log("2: " + value); // => 100 * 2 * 2
});

//控制台打印
1,100
2,400
```
> 如果我们知道了 `then` 方法每次都会创建并返回一个`新`的promise对象的话，那么我们就应该不难理解下面代码中对` then` 的使用方式上的差别了

<mark>then一个很重要的反例</mark>
```bash
function badAsyncCall() {
    var promise = Promise.resolve();
    promise.then(function() {
        // 任意处理
        return newVar;
    });
    return promise;
}
```
这种写法有很多问题，首先在 `promise.then` 中产生的异常不会被外部捕获，此外，也不能得到 `then` 的返回值，即使其有返回值。

由于每次 promise.then 调用都会返回一个新创建的promise对象，因此需要像上述方式2那样，采用promise chain的方式将调用进行链式化，修改后的代码如下所示。

<mark>正确写法</mark>
```bash
function anAsyncCall() {
    var promise = Promise.resolve();
    return promise.then(function() {
        // 任意处理
        return newVar;
    });
}

```
### Promise.all()

`Promise.all` 接收一个 `promise对象的数组`作为参数，当这个数组里的所有promise对象全部变为`resolve`或`reject`状态的时候，它才会去调用 `.then` 方法。

```bash
function getURL(URL) {
    return new Promise(function (resolve, reject) {
        var req = new XMLHttpRequest();
        req.open('GET', URL, true);
        req.onload = function () {
            if (req.status === 200) {
                resolve(req.responseText);
            } else {
                reject(new Error(req.statusText));
            }
        };
        req.onerror = function () {
            reject(new Error(req.statusText));
        };
        req.send();
    });
}
var request = {
        comment: function getComment() {
            return getURL('http://azu.github.io/promises-book/json/comment.json').then(JSON.parse);
        },
        people: function getPeople() {
            return getURL('http://azu.github.io/promises-book/json/people.json').then(JSON.parse);
        }
    };
function main() {
    //不采用all
    /**
    function recordValue(results, value) {
        results.push(value);
        return results;
    }
    // [] 用来保存初始化的值
    var pushValue = recordValue.bind(null, []);
    return request.comment().then(pushValue).then(request.people).then(pushValue);
    **/
    return Promise.all([request.comment(), request.people()]);
}
// 运行示例
main().then(function (value) {
    console.log(value);
}).catch(function(error){
    console.log(error);
});

```

在上面的代码中，`request.comment() `和 `request.people()` 会同时开始执行，而且每个promise的结果（resolve或reject时传递的参数值），和传递给 Promise.all 的promise数组的`顺序是一致`的。

也就是说，这时候` .then` 得到的promise数组的执行结果的顺序是`固定`的，即` [comment, people]`。
```bash
main().then(function (results) {
    console.log(results); // 按照[comment, people]的顺序
});
```
栗子🌰

```bash
// `delay`毫秒后执行resolve
function timerPromisefy(delay) {
    return new Promise(function (resolve) {
        setTimeout(function () {
            resolve(delay);
        }, delay);
    });
}
var startDate = Date.now();
// 所有promise变为resolve后程序退出
Promise.all([
    timerPromisefy(1),
    timerPromisefy(32),
    timerPromisefy(64),
    timerPromisefy(128)
]).then(function (values) {
    console.log(Date.now() - startDate + 'ms');
    // 約128ms
    console.log(values);    // [1,32,64,128]
});
//可用于多个请求之后，关闭弹出框之类的业务
```
### Promise.race()
`Promise.all` 在接收到的所有的对象promise都变为 FulFilled 或者 Rejected 状态之后才会继续进行后面的处理， 与之相对的是 `Promise.race` 只要有一个promise对象进入 FulFilled 或者 Rejected 状态的话，就会继续进行后面的处理。

```bash
// `delay`毫秒后执行resolve
function timerPromisefy(delay) {
    return new Promise(function (resolve) {
        setTimeout(function () {
            resolve(delay);
        }, delay);
    });
}
// 任何一个promise变为resolve或reject 的话程序就停止运行
Promise.race([
    timerPromisefy(1),
    timerPromisefy(32),
    timerPromisefy(64),
    timerPromisefy(128)
]).then(function (value) {
    console.log(value);    // => 1
});
```

```bash
var winnerPromise = new Promise(function (resolve) {
        setTimeout(function () {
            console.log('this is winner');
            resolve('this is winner');
        }, 4);
    });
var loserPromise = new Promise(function (resolve) {
        setTimeout(function () {
            console.log('this is loser');
            resolve('this is loser');
        }, 1000);
    });
// 第一个promise变为resolve后程序停止
Promise.race([winnerPromise, loserPromise]).then(function (value) {
    console.log(value);    // => 'this is winner'
});
```
`Promise.race`并不会在第一个promise变为Fulfilled时，取消其他promise的运行，~~但是resolve的结果却是只有第一个的，赛跑赛跑）~~

### 不能进行错误处理的onRejected

```bash
function throwError(value) {
    // 抛出异常
    throw new Error(value);
}
// <1> onRejected不会被调用
function badMain(onRejected) {
    return Promise.resolve(42).then(throwError, onRejected);
}
// <2> 有异常发生时onRejected会被调用
function goodMain(onRejected) {
    return Promise.resolve(42).then(throwError).catch(onRejected);
}
// 运行示例
badMain(function(){
    console.log("BAD");
});
goodMain(function(){
    console.log("GOOD");
});
```
> 为什么说 `badMain` 不好呢？，因为虽然我们在`.then` 的第二个参数中指定了用来错误处理的函数，但实际上它却不能捕获第一个参数 `onFulfilled` 指定的函数（本例为 `throwError` ）里面出现的错误。
也就是说，这时候即使 `throwError` 抛出了异常，onRejected 指定的函数也不会被调用（即不会输出`"BAD"`字样）。
与此相对的是， `goodMain` 的代码则遵循了 `throwError→onRejected` 的调用流程。 这时候 `throwError` 中出现异常的话，在会被方法链中的下一个方法，即 `.catch` 所捕获，进行相应的错误处理。

**我们需要注意如果代码类似 badMain 那样的话，就可能出现程序不会按预期运行的情况，从而不能正确的进行错误处理。**

### 简单的thenable

```bash
// 返回 `thenable`
function notifyMessageAsThenable(message, options) {
    return {
        'then': function (resolve, reject) {
            notifyMessage(message, options, function (error, notification) {
                if (error) {
                    reject(error);
                } else {
                    resolve(notification);
                }
            });
        }
    };
}
// 运行示例
Promise.resolve(notifyMessageAsThenable("message")).then(function (notification) {
    console.log(notification);// 通知对象
}).catch(function(error){
    console.error(error);
});
```

### Deferred和Promise的关系

![image](http://liubin.org/promises-book/Ch4_AdvancedPromises/img/deferred-and-promise.png)

### 让Promise等待指定时间
- 简单的🌰
```bash
function delayPromise(ms){
    return new Promise(function(){
        setTimeout(resolve,ms);
    })
}
//栗子🌰
delayPromise(100).then(function(){
    alert('已经延迟100ms')
)
```
-  Promise.race中的超时

```bash
function delayPromise(ms) {
    return new Promise(function (resolve) {
        setTimeout(resolve, ms);
    });
}
function timeoutPromise(promise, ms) {
    var timeout = delayPromise(ms).then(function () {
            throw new Error('Operation timed out after ' + ms + ' ms');
        });
    return Promise.race([promise, timeout]);
}
// 运行示例
var taskPromise = new Promise(function(resolve){
    // 随便一些什么处理
    var delay = Math.random() * 2000;
    setTimeout(function(){
        resolve(delay + "ms");
    }, delay);
});
timeoutPromise(taskPromise, 1000).then(function(value){
    console.log("taskPromise在规定时间内结束 : " + value);
}).catch(function(error){
    console.log("发生超时", error);
});
```












[](http://liubin.org/promises-book/#promises-aplus)




